title: Your awesome title
author: Pytrick li
email: youremail@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  this is a samle website, hope you enjoy it.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
